export const books = [
  {
    id: '1',
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    publishingDate: '29-07-1954',
    price: 29.99,
    stock: 10,
    description: 'An epic high-fantasy novel set in Middle-earth.',
    coverImageUrl: '/images/lord-of-the-rings.jpg',
  },
  {
    id: '2',
    title: 'Lord of the Flies',
    author: 'William Golding',
    genre: 'Fiction',
    publishingDate: '17-09-1954',
    price: 14.99,
    stock: 15,
    description:
      'A novel about a group of boys stranded on an uninhabited island.',
    coverImageUrl: '/images/lord-of-the-flies.jpg',
  },
  {
    id: '3',
    title: 'Joy of Cooking',
    author: 'Irma S. Rombauer',
    genre: 'Cooking',
    publishingDate: '01-01-1931',
    price: 39.99,
    stock: 5,
    description: 'A classic recipe book with a wide variety of dishes.',
    coverImageUrl: '/images/joy-of-cooking.jpg',
  },
  {
    id: '4',
    title: 'The Eye of the World',
    author: 'Robert Jordan',
    genre: 'Fantasy',
    publishingDate: '15-01-1990',
    price: 24.99,
    stock: 8,
    description: 'The first book in the epic Wheel of Time series.',
    coverImageUrl: '/images/eye-of-the-world.png',
  },
  {
    id: '5',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    genre: 'Fiction',
    publishingDate: '11-07-1960',
    price: 18.99,
    stock: 12,
    description: 'A novel about racial injustice in the Deep South.',
    coverImageUrl: '/images/to-kill-a-mockingbird.png',
  },
];
